# Minecraft / Mappings
minecraft_version=1.21.1
minecraft_version_support_range=>=1.21.1
parchment_version=parchment-1.21.1:2024.11.17

# Fabric
loader_version=0.16.14
fabric_version=0.116.4+1.21.1

# Mod Properties
mod_id=playerdisguise
mod_version=0.1.0
maven_group=com.weaversworkshop.playerdisguise
archives_base_name=playerdisguise

# Compilation
show_dev_warnings=false
