modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "MPL-2.0"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Player Disguise"
authors = "Weaver's Workshop"
description = '''
Pick a name. Pick a skin. Become anybody.

Player Disguise lets you assume an alias and custom skin while playing. Chat, tab list, nameplate, and visuals update for everyone on the server. Ops keep full visibility through /whois and /namehistory for moderation.
Skins stay server-side with persistent claims, cooldowns on release, and zero outbound traffic.
'''

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mixins]]
config = "playerdisguise.mixins.json"

[[mixins]]
config = "playerdisguise.voicechat.mixins.json"

[[mixins]]
config = "playerdisguise.bluemap.mixins.json"

[[mixins]]
config = "playerdisguise.journeymap.mixins.json"

[[mixins]]
config = "playerdisguise.chatheads.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_support_range}"
ordering = "NONE"
side = "BOTH"
