modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "All Rights Reserved"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Player Disguise"
authors = "Weaver's Workshop"
description = '''
Disguise yourself as other players.
'''

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_support_range}"
ordering = "NONE"
side = "BOTH"
